### ISSUE TITLE
bind 9.6 - pyparsing.ParseException: Expected end of text, found '{'

### ISSUE THREAD

**Issue by fdebonneval** [egberts/bind9_parser#5]
Hi egberts,

Sorry to bother, but I spent some time trying to debug my issue with no luck.
When I give the top of my (old BIND 9.6.-ESV-R3) named.conf, I get the error bellow.

I tried to clean the file form special / invisible chars. But it looks like it is a syntax issue ...
If I remove the ' acl "ripe-hostcount"' line, it breaks on 'acl "bogon" {' 
Maybe you have an idea ?

Thanks a lot.
F

log from `parse_bind9.py`
```
root@39448b75c10c:/bind9_parser/examples# ./parse_bind9.py /data/production-data/namedb/named.conf
Start: Is the library quiet?
Traceback (most recent call last):
  File "./parse_bind9.py", line 268, in <module>
    result = my_clauses.parseString(toplevel_config, parseAll=True)
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found '{'  (at char 862), (line:17, col:22)
```

Extract from my named.conf :
```
key "rndc-key" { algorithm hmac-sha256; secret "iQxBKDHuO62ECsjuWkrKzfC1FFmYF3C/5Wb8sR/MSZU="; };controls { inet 127.0.0.1 port 953 allow { 127.0.0.1; } keys { "rndc-key"; };}; logging { channel query_log  { file "/etc/namedb/log/named.log" versions 12 size 100m; print-time yes; };
category default { query_log; default_syslog; default_debug;};
category lame-servers { query_log; default_syslog; default_debug;};
category config { query_log; default_syslog; default_debug;};
category update { query_log; default_syslog; default_debug;};
category update-security { query_log; default_syslog; default_debug;};
category notify { query_log; default_syslog; default_debug;};
category queries { query_log; };
};



acl "ok" { any; };
acl "nok" { none; };
acl "auth-temp-pub" { 192.168.254.40; 192.168.254.41; };
acl "auth-temp-priv" { 192.168.3.171;  192.168.3.172; };
acl "ripe-hostcount" { 193.0.0.0/22; 91.121.158.151; 2001:610:240::/48; 2001:67c:2e8::/48; };

acl "bogon" {
// Filter out the bogon networks.  These are networks
// listed by IANA as test, RFC1918, Multicast, experi-
// mental, etc.  If you see DNS queries or updates with
// a source address within these networks, this is likely
// of malicious origin. CAUTION: If you are using RFC1918
// netblocks on your network, remove those netblocks from
// this list of blackhole ACLs!
0.0.0.0/8;
169.254.0.0/16;
192.0.0.0/24;
192.0.2.0/24;
198.18.0.0/15;
198.51.100.0/24;
203.0.113.0/24;
240.0.0.0/4;
//10.0.0.0/8;
//192.168.0.0/16;
//172.16.0.0/12;
};

options {
// Relative to the chroot directory, if any
directory       "/etc/namedb";
pid-file        "/var/run/named/pid";
dump-file       "/etc/namedb/log/named_dump.db";
statistics-file "/etc/namedb/log/named.stats";
memstatistics-file "/etc/namedb/log/named-mem.stats";
zone-statistics yes;
listen-on       { 127.0.0.1; 192.168.254.1; };
//      listen-on-v6    { ::1; };
version	"none";
interface-interval 0;
transfers-in 15;
transfers-out 15;
transfers-per-ns 15;
recursive-clients 20000;
```

**Comment by egberts** [comment]
Ok, a couple of things...  Firstly, I've recreated your error so I have something to work with.

On a side note....
1. I used my (new Vim syntax highlighter)[https://github.com/egberts/vim-syntax-bind-named] on your named.conf to catch a few 'errors'  I don't know if your original named.conf is a victim of cut-n-paste operation into this issue, or not.
  a. I made a new line for `controls` statement,
  b. Added a new line for `key` statement
  c. Added missing '};' to EOF.

This resulted in me fixing my Vim syntax  #highlighter
  c. (Added support)[https://github.com/egberts/vim-syntax-bind-named/issues/4#issue-606373994] any-quote for `key` and `acl` identifier.

Now, back to troubleshooting this issue.

**Comment by egberts** [comment]
I see that commenting out the offending line, made 'it work'.
```named
acl "ok" { any; };
acl "nok" { none; };
acl "auth-temp-pub" { 192.168.254.40; 192.168.254.41; };
acl "auth-temp-priv" { 192.168.3.171;  192.168.3.172; };
//acl "ripe-hostcount" { 193.0.0.0/22; 91.121.158.151; 2001:610:240::/48; 2001:67c:2e8::/48; };
```
which resulted in the following:
```python
print(result.asDict()):
{   'acl': [   {   'acl_name': '"bogon"',
                   'aml_series': [   {   'aml': [   {   'addr': '0.0.0.0/8'},
                                                    {   'addr': '169.254.0.0/16'},
                                                    {   'addr': '192.0.0.0/24'},
                                                    {   'addr': '192.0.2.0/24'},
                                                    {   'addr': '198.18.0.0/15'},
                                                    {   'addr': '198.51.100.0/24'},
                                                    {   'addr': '203.0.113.0/24'},
                                                    {   'addr': '240.0.0.0/4'}]}]}],
    'controls': [   {   'inet': {   'allow': {   'aml': [   {   'addr': '127.0.0.1'}]},
                                    'control_server_addr': '127.0.0.1',
                                    'ip_port_w': 953,
                                    'keys': [   {   'key_id': '"rndc-key"'}]}}],
    'key': [   {   'algorithm': 'hmac-sha256',
                   'key_id': '"rndc-key"',
                   'secret': '"iQxBKDHuO62ECsjuWkrKzfC1FFmYF3C/5Wb8sR/MSZU="'}],
    'logging': [   {   'channel': [   {   'channel_name': 'query_log',
                                          'path_name': '"/etc/namedb/log/named.log"',
                                          'print_time': 'yes',
                                          'size_spec': [   100,
                                                           'm'],
                                          'versions': 12}]},
                   {   'category_group': [   {   'categories': [   'query_log',
                                                                   'default_syslog',
                                                                   'default_debug'],
                                                 'category_group_name': 'default'}]},
                   {   'category_group': [   {   'categories': [   'query_log',
                                                                   'default_syslog',
                                                                   'default_debug'],
                                                 'category_group_name': 'lame-servers'}]},
                   {   'category_group': [   {   'categories': [   'query_log',
                                                                   'default_syslog',
                                                                   'default_debug'],
                                                 'category_group_name': 'config'}]},
                   {   'category_group': [   {   'categories': [   'query_log',
                                                                   'default_syslog',
                                                                   'default_debug'],
                                                 'category_group_name': 'update'}]},
                   {   'category_group': [   {   'categories': [   'query_log',
                                                                   'default_syslog',
                                                                   'default_debug'],
                                                 'category_group_name': 'update-security'}]},
                   {   'category_group': [   {   'categories': [   'query_log',
                                                                   'default_syslog',
                                                                   'default_debug'],
                                                 'category_group_name': 'notify'}]},
                   {   'category_group': [   {   'categories': [   'query_log'],
                                                 'category_group_name': 'queries'}]}],
    'options': [   {   'directory': '"/etc/namedb"',
                       'dump_file': '"/etc/namedb/log/named_dump.db"',
                       'interface_interval': 0,
                       'listen_on': [   {   'aml': [   {   'addr': '127.0.0.1'},
                                                       {   'addr': '192.168.254.1'}]}],
                       'memstatistics_file': '"/etc/namedb/log/named-mem.stats"',
                       'pid_file_path_name': '"/var/run/named/pid"',
                       'recursive_clients': 20000,
                       'statistics_file_path_name': '"/etc/namedb/log/named.stats"',
                       'transfers_in': 15,
                       'transfers_out': 15,
                       'transfers_per_ns': 15,
                       'version_string': '"none"',
                       'zone_statistics': 'yes'}]}
```

Narrowing it down...by commenting out the two IPv6 from:
```named
acl "ripe-hostcount" { 193.0.0.0/22; 91.121.158.151; /* 2001:610:240::/48;
2001:67c:2e8::/48; */ };
```
That works.

Try second/last IPv6 commented out...thus restoring the 1st IPv6.  And same error message as this issue.
```shell
pyparsing.ParseException: Expected end of text, found '{'  (at char 887), (line:19, col:22)
```
(stay tune)

**Comment by fdebonneval** [comment]
Take all the time you need ;)
Already; thanks for the troubleshoot

**Comment by egberts** [comment]
Thankfully that PyCharm can highlight what more unit tests that I need to flesh out (see darkened white).

![Screenshot_20200424_112539](https://user-images.githubusercontent.com/10352354/80229374-db634880-863f-11ea-9d8e-9d26e15bc771.png)

**Comment by egberts** [comment]
Added issue #8 for additional unit test

**Comment by egberts** [comment]
I added github-issue-8.named.conf to my `tests/github-issues` subdirectory.
Commented out the IPv6 for now...  (We will get back to that later).

```bash
cd bind9_parser/tests/github-issues/
../../examples/parse_bind9.py ./github-issue-8.named.conf 
```
`parse_bind9.py` outputs both the Python list content:
```python
[['"rndc-key"',
  'hmac-sha256',
  '"iQxBKDHuO62ECsjuWkrKzfC1FFmYF3C/5Wb8sR/MSZU="'],
 [[['127.0.0.1', 953, [['127.0.0.1']], ['"rndc-key"']]]],
 [[['query_log', '"/etc/namedb/log/named.log"', 12, 100, 'm', 'yes']],
  [['default', 'query_log', 'default_syslog', 'default_debug']],
  [['lame-servers', 'query_log', 'default_syslog', 'default_debug']],
  [['config', 'query_log', 'default_syslog', 'default_debug']],
  [['update', 'query_log', 'default_syslog', 'default_debug']],
  [['update-security', 'query_log', 'default_syslog', 'default_debug']],
  [['notify', 'query_log', 'default_syslog', 'default_debug']],
  [['queries', 'query_log']]],
 ['"ok"', [['any']]],
 ['"nok"', [['none']]],
 ['"auth-temp-pub"', [['192.168.254.40'], ['192.168.254.41']]],
 ['"auth-temp-priv"', [['192.168.3.171'], ['192.168.3.172']]],
 ['"ripe-hostcount"', [['193.0.0.0/22'], ['91.121.158.151']]],
 ['"bogon"',
  [['0.0.0.0/8'],
   ['169.254.0.0/16'],
   ['192.0.0.0/24'],
   ['192.0.2.0/24'],
   ['198.18.0.0/15'],
   ['198.51.100.0/24'],
   ['203.0.113.0/24'],
   ['240.0.0.0/4']]],
 ['"/etc/namedb"',
  '"/var/run/named/pid"',
  '"/etc/namedb/log/named_dump.db"',
  '"/etc/namedb/log/named.stats"',
  '"/etc/namedb/log/named-mem.stats"',
  'yes',
  [['127.0.0.1'], ['192.168.254.1']],
  '"none"',
  0,
  15,
  15,
  15,
  20000]]
```
and the Python dictionary content as well:
```Python
{'key': [{'key_id': '"rndc-key"', 'algorithm': 'hmac-sha256', 'secret': '"iQxBKDHuO62ECsjuWkrKzfC1FFmYF3C/5Wb8sR/MSZU="'}], 'controls': [{'inet': {'control_server_addr': '127.0.0.1', 'ip_port_w': 953, 'allow': {'aml': [{'addr': '127.0.0.1'}]}, 'keys': [{'key_id': '"rndc-key"'}]}}], 'logging': [{'channel': [{'channel_name': 'query_log', 'path_name': '"/etc/namedb/log/named.log"', 'versions': 12, 'size_spec': [100, 'm'], 'print_time': 'yes'}]}, {'category_group': [{'category_group_name': 'default', 'categories': ['query_log', 'default_syslog', 'default_debug']}]}, {'category_group': [{'category_group_name': 'lame-servers', 'categories': ['query_log', 'default_syslog', 'default_debug']}]}, {'category_group': [{'category_group_name': 'config', 'categories': ['query_log', 'default_syslog', 'default_debug']}]}, {'category_group': [{'category_group_name': 'update', 'categories': ['query_log', 'default_syslog', 'default_debug']}]}, {'category_group': [{'category_group_name': 'update-security', 'categories': ['query_log', 'default_syslog', 'default_debug']}]}, {'category_group': [{'category_group_name': 'notify', 'categories': ['query_log', 'default_syslog', 'default_debug']}]}, {'category_group': [{'category_group_name': 'queries', 'categories': ['query_log']}]}], 'acl': [{'acl_name': '"bogon"', 'aml_series': [{'aml': [{'addr': '0.0.0.0/8'}, {'addr': '169.254.0.0/16'}, {'addr': '192.0.0.0/24'}, {'addr': '192.0.2.0/24'}, {'addr': '198.18.0.0/15'}, {'addr': '198.51.100.0/24'}, {'addr': '203.0.113.0/24'}, {'addr': '240.0.0.0/4'}]}]}], 'options': [{'directory': '"/etc/namedb"', 'pid_file_path_name': '"/var/run/named/pid"', 'dump_file': '"/etc/namedb/log/named_dump.db"', 'statistics_file_path_name': '"/etc/namedb/log/named.stats"', 'memstatistics_file': '"/etc/namedb/log/named-mem.stats"', 'zone_statistics': 'yes', 'listen_on': [{'aml': [{'addr': '127.0.0.1'}, {'addr': '192.168.254.1'}]}], 'version_string': '"none"', 'interface_interval': 0, 'transfers_in': 15, 'transfers_out': 15, 'transfers_per_ns': 15, 'recursive_clients': 20000}]}
```
PrettyPrint output for the above Python dictionary content is:
```
print(result.asDict()):
{'acl': [{'acl_name': '"bogon"',
          'aml_series': [{'aml': [{'addr': '0.0.0.0/8'},
                                  {'addr': '169.254.0.0/16'},
                                  {'addr': '192.0.0.0/24'},
                                  {'addr': '192.0.2.0/24'},
                                  {'addr': '198.18.0.0/15'},
                                  {'addr': '198.51.100.0/24'},
                                  {'addr': '203.0.113.0/24'},
                                  {'addr': '240.0.0.0/4'}]}]}],
 'controls': [{'inet': {'allow': {'aml': [{'addr': '127.0.0.1'}]},
                        'control_server_addr': '127.0.0.1',
                        'ip_port_w': 953,
                        'keys': [{'key_id': '"rndc-key"'}]}}],
 'key': [{'algorithm': 'hmac-sha256',
          'key_id': '"rndc-key"',
          'secret': '"iQxBKDHuO62ECsjuWkrKzfC1FFmYF3C/5Wb8sR/MSZU="'}],
 'logging': [{'channel': [{'channel_name': 'query_log',
                           'path_name': '"/etc/namedb/log/named.log"',
                           'print_time': 'yes',
                           'size_spec': [100,
                                         'm'],
                           'versions': 12}]},
             {'category_group': [{'categories': ['query_log',
                                                 'default_syslog',
                                                 'default_debug'],
                                  'category_group_name': 'default'}]},
             {'category_group': [{'categories': ['query_log',
                                                 'default_syslog',
                                                 'default_debug'],
                                  'category_group_name': 'lame-servers'}]},
             {'category_group': [{'categories': ['query_log',
                                                 'default_syslog',
                                                 'default_debug'],
                                  'category_group_name': 'config'}]},
             {'category_group': [{'categories': ['query_log',
                                                 'default_syslog',
                                                 'default_debug'],
                                  'category_group_name': 'update'}]},
             {'category_group': [{'categories': ['query_log',
                                                 'default_syslog',
                                                 'default_debug'],
                                  'category_group_name': 'update-security'}]},
             {'category_group': [{'categories': ['query_log',
                                                 'default_syslog',
                                                 'default_debug'],
                                  'category_group_name': 'notify'}]},
             {'category_group': [{'categories': ['query_log'],
                                  'category_group_name': 'queries'}]}],
 'options': [{'directory': '"/etc/namedb"',
              'dump_file': '"/etc/namedb/log/named_dump.db"',
              'interface_interval': 0,
              'listen_on': [{'aml': [{'addr': '127.0.0.1'},
                                     {'addr': '192.168.254.1'}]}],
              'memstatistics_file': '"/etc/namedb/log/named-mem.stats"',
              'pid_file_path_name': '"/var/run/named/pid"',
              'recursive_clients': 20000,
              'statistics_file_path_name': '"/etc/namedb/log/named.stats"',
              'transfers_in': 15,
              'transfers_out': 15,
              'transfers_per_ns': 15,
              'version_string': '"none"',
              'zone_statistics': 'yes'}]}
```

Since I'm still working on IPv6 (Issue #8)... I haven't forgotten you.

**Comment by egberts** [comment]
that should fix it.
